name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo add-apt-repository universe
        sudo apt-get install -y powershell
        pwsh -command "Install-Module PSScriptAnalyzer -Force"
        pwsh -command "Invoke-ScriptAnalyzer -Path ./Set-TerminalGif.ps1"

