name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo "Hello-World"
        echo "Hello-World 2"
